import frappe


def execute():
    reports_moved = {
        "Batch Status" : "Stock",
        "Stock Balance without WIP" : "Stock",
        "PO Register" : "Buying",
        "Semi Finished Production" : "Manufacturing",
        "MRN Against Delivery Note DFM" : "Stock",
        "Journal Entry Register -DFM" : "Accounts",
        "Gate Entry Register DFM" : "Stock",
        "Daily Timesheet Summary" : "Projects",
        "Item Batch Expiry Status DFM" : "Stock",
        "Unauthorized PO DFM" : "Buying",
        "Supplier List DFM" : "Buying",
        "Quotation Register DFM" : "Buying",
        "Material Issue DFM" : "Stock",
        "Item Batch Expiry Within 16 - 30 days DFM-2" : "Stock",
        "Item Balance (Simple)" : "Stock",
        "Purchase Order Items To Be Billed" : "Accounts",
        "Debit Note Register DFM" : "Stock",
        "Store Stock" : "Stock",
        "Item Batch Expiry Within 15 days DFM" : "Stock",
        "Material Request DFM" : "Stock",
        "Review" : "Quality Management",
        "Supplier Quotation Comparison" : "Buying",
        "Production Consumption Report DFM" : "Stock",
        "FG Production" : "Manufacturing",
        "Material Transfer for MFG DFM" : "Stock",
        "Purchase Return DFM" : "Stock",
        "User Role & Permission DFM" : "Core",
        "Stock Ledger for Store" : "Stock",
        "Material Transfer DFM" : "Stock",
        "Quality Inspection DFM" : "Stock",
        "BOM Vs Actual 2" : "Manufacturing",
        "Purchase Order Register Report" : "Buying",
        "Plant Transfer DFM" : "Stock",
        "PO Reg" : "Buying",
        "Electronic Invoice Register" : "Regional",
        "Purchase Invoice Register DFM" : "Accounts",
        "GIN Register DFM" : "Stock",
        "QC Pending DFM" : "Stock",
        "Item List DFM" : "Stock",
        "Warehouse Linewise Report" : "Stock",
        "Item Batch Expiry Within 7 Days DFM" : "Stock",
        "Trial Balance (Simple)" : "Accounts",
        "Stock Balance 2" : "Stock",
        "BOM List" : "Manufacturing",
        "Payment Entry- Register DFM" : "Accounts",
        "Production Consumption 2" : "Stock",
        "Purchase Invoice Register Without GST" : "Accounts",
        "Purchase Order Items To Be Received" : "Stock",
        "Stock Ledger for Accounts Summary" : "Stock",
        "Item Batch Expiry Within 16 - 30 days DFM" : "Stock",
        "Issues Action Tracker" : "Support",
        "Purchase Order Register" : "Buying",
        "MRN Register DFM" : "Stock",
        "WIP QC Report" : "Stock",
        "Quotation Comparison DFM" : "Buying",
        "BOM Vs Actual" : "Manufacturing",
        "Purchase Order Items To Be Received or Billed" : "Stock",
        "Item Batch Expiry Within 15 days DFM-2" : "Stock",
        "Production Consumption 3" : "Stock",
        "User Activity Log Report" : "Core",
        "Support Ticket Report" : "Support",
        "GIN Register" : "Buying"
    }
    for report, module in reports_moved.items():
		frappe.delete_doc_if_exists("Report", {"name": report, "module": module})